# Generated by Django 6.1.1 on 2026-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShogiGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_color', models.CharField(choices=[('black', '先手'), ('white', '後手')], max_length=5)),
                ('agent', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('moves', models.TextField(blank=True, default='')),
                ('result', models.CharField(blank=True, choices=[('human_win', '人の勝ち'), ('ai_win', 'AI の勝ち'), ('draw', '引き分け')], default='', max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=50)),
                ('last_ai', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
