# Generated by Django 6.1.1 on 2026-09-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('playing', '対戦中')], default='waiting', max_length=10)),
                ('seed', models.BigIntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('winner_name', models.CharField(max_length=20)),
                ('loser_name', models.CharField(max_length=20)),
                ('winner_slot', models.IntegerField()),
                ('reason', models.CharField(choices=[('topout', '相手がゲームオーバー'), ('disconnect', '相手が切断')], max_length=12)),
                ('duration_sec', models.FloatField(default=0)),
                ('stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tetris_online.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('channel_name', models.CharField(max_length=200)),
                ('ready', models.BooleanField(default=False)),
                ('alive', models.BooleanField(default=True)),
                ('wins', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tetris_online.room')),
            ],
            options={
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('room', 'slot'), name='uniq_room_slot')],
            },
        ),
    ]
