# Generated by Django 6.1.1 on 2026-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetris_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.CharField(default='tetris', max_length=20),
        ),
    ]
