# Generated by Django 6.1.1 on 2026-09-20 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokerTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(max_length=100)),
                ('start_stack', models.IntegerField()),
                ('stacks', models.JSONField(default=list)),
                ('hand_no', models.IntegerField(default=0)),
                ('state', models.JSONField(blank=True, null=True)),
                ('hist', models.CharField(default='', max_length=128)),
                ('log', models.JSONField(default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PokerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_no', models.IntegerField()),
                ('agent', models.CharField(max_length=100)),
                ('stack_bb', models.IntegerField()),
                ('human_payoff', models.IntegerField()),
                ('pot', models.IntegerField()),
                ('showdown', models.BooleanField()),
                ('board', models.CharField(blank=True, max_length=32)),
                ('human_hole', models.CharField(max_length=8)),
                ('ai_hole', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='poker.pokertable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
