# Generated by Django 6.1.1 on 2026-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='ai_memo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
