# Generated by Django 6.1.1 on 2026-09-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('game', '対局'), ('client_error', '画面のエラー'), ('server_error', 'サーバーのエラー')], max_length=20)),
                ('game', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('path', models.CharField(max_length=200)),
                ('game', models.CharField(blank=True, max_length=30)),
                ('device', models.CharField(max_length=10)),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
