# Generated by Django 6.1.1 on 2026-09-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict)),
                ('metrics_offset', models.BigIntegerField(default=0)),
                ('evals_offset', models.BigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['game', '-synced_at'],
                'constraints': [models.UniqueConstraint(fields=('game', 'name'), name='uniq_game_run')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('data', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingrun')),
            ],
            options={
                'ordering': ['episode'],
                'constraints': [models.UniqueConstraint(fields=('run', 'episode'), name='uniq_run_metric')],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('step', models.IntegerField(default=0)),
                ('checkpoint', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('is_best', models.BooleanField(default=False)),
                ('results', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training.trainingrun')),
            ],
            options={
                'ordering': ['episode'],
                'constraints': [models.UniqueConstraint(fields=('run', 'episode'), name='uniq_run_evaluation')],
            },
        ),
    ]
