# Generated by Django 6.1.1 on 2026-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OthelloGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.CharField(max_length=128)),
                ('human_color', models.CharField(choices=[('black', '黒（先手）'), ('white', '白（後手）')], max_length=5)),
                ('agent', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('black_discs', models.IntegerField()),
                ('white_discs', models.IntegerField()),
                ('human_result', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
