# Generated by Django 6.1.1 on 2026-09-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('car', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=100)),
                ('laps', models.IntegerField()),
                ('total_sec', models.FloatField()),
                ('best_lap_sec', models.FloatField()),
                ('tricks', models.IntegerField(default=0)),
                ('falls', models.IntegerField(default=0)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('racers', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
